server:
  servlet:
    context-path: /starwars-api

swapi:
  url: https://swapi.dev/api
  # url: https://swapi-deno.azurewebsites.net/api

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:starwarsapidb