server:
  servlet:
    context-path: /starwars-api

swapi:
  url: https://swapi.dev/api
  # url: https://swapi-deno.azurewebsites.net/api

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:starwarsapidb
  output:
  ansi:
    enabled: DETECT

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN
        cache : TRACE
      hibernate: WARN
    br:
      com:
        massao: DEBUG


